version: '3.8'

services:
  opencode:
    image: ghcr.io/anomalyco/opencode:latest
    # Ou build local si vous avez le code source :
    # build:
    #   context: ../opencode-dev/packages/opencode
    #   dockerfile: Dockerfile

    container_name: opencode-server

    ports:
      - "3000:3000"  # API REST + SSE

    volumes:
      # Stockage persistant des sessions et logs
      - opencode-data:/data/opencode

      # Projet à analyser (à adapter selon vos besoins)
      - ../workspace:/workspace:rw

      # Configuration OpenCode (optionnel)
      # - ../opencode-dev/opencode.json:/root/.config/opencode/opencode.json:ro

    environment:

      # Répertoire de données
      - OPENCODE_DATA_DIR=/data/opencode

      # URL d'Ollama (si sur l'hôte)
      - OLLAMA_BASE_URL=http://host.containers.internal:11434/v1

    # Accès au réseau hôte pour Ollama
    extra_hosts:
      - "host.containers.internal:host-gateway"

    # Commande de démarrage
    command: ["serve", "--host", "0.0.0.0", "--port", "3000"]

    restart: unless-stopped

    # Healthcheck
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/session"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s


volumes:
  opencode-data:
    driver: local
  # ollama-data:
  #   driver: local
